CREATE DATABASE LAB1;

CREATE TABLE USERS(
    id INT PRIMARY KEY,
    firstname VARCHAR(50),
    lastname VARCHAR(50)
);

ALTER TABLE USERS ADD COLUMN isadmin INT;

ALTER TABLE USERS ALTER COLUMN isadmin TYPE BOOLEAN USING isadmin::boolean;

ALTER TABLE USERS ALTER COLUMN isadmin SET DEFAULT false;

ALTER TABLE USERS ADD CONSTRAINT cont PRIMARY KEY (id);

CREATE TABLE tasks(
    id INT PRIMARY KEY,
    name VARCHAR(50),
    USER_ID INT
);

DROP TABLE tasks;

DROP DATABASE LAB1;

SELECT * FROM tasks;